services:
  dev:
    container_name: ${KAGGLE_COMPETITION_NAME}_dev
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '64gb'
    volumes:
      - type: bind
        source: $PWD
        target: /kaggle/working
      - type: volume
        source: venv
        target: /kaggle/working/.venv
    working_dir: /kaggle/working
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

volumes:
  venv:
