data_dir: /kaggle/input/eedi-mining-misconceptions-in-mathematics
train_csv_path: ${dir.data_dir}/train.csv
test_csv_path: ${dir.data_dir}/test.csv
misconception_csv_path: ${dir.data_dir}/misconception_mapping.csv
submission_csv_path: ${dir.data_dir}/sample_submission.csv
